# Generated by Django 4.1.3 on 2022-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_avatar_myuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
