# Generated by Django 4.1.3 on 2022-11-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
